
/**
 * The proxy server URL.
 */
export const PROXY_SERVER = 'https://learner-gateway.uc.r.appspot.com/';
// export const PROXY_SERVER = 'http://127.0.0.1:3000/';

/**
 * The firebase configuration. the apiKey is an id of the project, not a securit key, 
 * so it's okay to check in the code. This object is generated by Firebase service,
 * don't change any name and value of it.
 */
export const environment = {
  production: false,
  firebase: {
    apiKey: "AIzaSyDjFOn3ls8rqd_LVEl3wkHWL4SX6XGoVc4",
    authDomain: "pingster-db.firebaseapp.com",
    projectId: "pingster-db",
    storageBucket: "pingster-db.firebasestorage.app",
    messagingSenderId: "318746586861",
    appId: "1:318746586861:web:e3d6e8e640c361e72726e4",
    measurementId: "G-J9PHZ5WB0J"
  },

  greetingImages: 'greeting-images',
  categories: 'categories',
  words: 'words',

  wordImgDir: 'assets/images/chars/',
  greetingImgDir: 'assets/images/greetings/',

  proxy: PROXY_SERVER,
  services: {
    tts: PROXY_SERVER + 'tts',
    stt: PROXY_SERVER + 'stt',
    pinyin: PROXY_SERVER + 'pinyin'
  }
};
